// Code generated by hertz generator.

package api

import (
	"context"
	"github.com/FantasyRL/go-mcp-demo/api/pack"
	"github.com/FantasyRL/go-mcp-demo/internal/host"

	api "github.com/FantasyRL/go-mcp-demo/api/model/api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Chat .
// @router /api/v1/chat [POST]
func Chat(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ChatRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.ChatResponse)
	msg, err := host.NewHost(ctx, clientSet).Chat(1, req.Message)
	if err != nil {
		pack.RespError(c, err)
		return
	}
	resp.Response = msg
	pack.RespData(c, resp)
}
