// Code generated by hertz generator.

package api

import (
	"context"

	api "github.com/FantasyRL/go-mcp-demo/api/model/api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Chat .
// @router /api/v1/chat [POST]
func Chat(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ChatRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.ChatResponse)

	c.JSON(consts.StatusOK, resp)
}
