// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
)

// register registers all routers.
func Register(r *server.Hertz) {
	GeneratedRegister(r)
	customizedRegister(r)
}
